package com.app.db;

import java.sql.SQLException;
import java.util.List;

import javax.sql.DataSource;

import org.apache.commons.dbutils.*;
import org.apache.commons.dbutils.handlers.*;

import com.app.bean.vm.VMLogin;

public class DbTest {

	private DbConfigHelper dbConfig = null;

	public DbTest(DbConfigHelper dbConfig) {
		this.dbConfig = dbConfig;
	}

	public List<VMLogin> TestX() throws SQLException {

		DataSource dataSource = new com.app.db.DataSource(this.dbConfig).getBds();

		QueryRunner run = new QueryRunner(dataSource);

		// Use the BeanListHandler implementation to convert all
		// ResultSet rows into a List of Person JavaBeans.
		ResultSetHandler<List<VMLogin>> h = new BeanListHandler<VMLogin>(VMLogin.class);

		// Execute the SQL statement and return the results in a List of
		// Person objects generated by the BeanListHandler.
		List<VMLogin> login = run.query("SELECT ename as userName,cast(deptno as varchar) as password from emp;", h);

		return login;
	}
	
	public String Test() throws SQLException {

		DataSource dataSource = new com.app.db.DataSource(this.dbConfig).getBds();

		QueryRunner run = new QueryRunner(dataSource,true);
		// Use the BeanListHandler implementation to convert all
		// ResultSet rows into a List of Person JavaBeans.
		ScalarHandler<String> h = new ScalarHandler<String>();

		// Execute the SQL statement and return the results in a List of
		// Person objects generated by the BeanListHandler.
		String result = run.query("SELECT @@VERSION ", h);

		return result;
	}
}
